apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-web-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-web-development
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: project-web-development
    spec:
      containers:
        - name: app
          image: learnforward2022/project-web-development:a33b39c500bef2aee9492d4253bfb6356907f2a8
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-web # for production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-web
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: project-web
    spec:
      containers:
        - name: app
          image: learnforward2022/project-web:f86245dbd853a5cf5acf434146959d303a062c67
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
