apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-web-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-web-development
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: project-web-development
    spec:
      containers:
        - name: app
          image: learnforward2022/project-web-development:8b2a2fdfd2c9c16a7c003d5933b2f25f041ff370
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-web # for production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-web
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: project-web
    spec:
      containers:
        - name: app
          image: learnforward2022/project-web:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
