apiVersion: v1
kind: Service
metadata:
  name: project-web-development-loadbalancer
spec:
  selector:
    app: project-web-development
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: project-web-loadbalancer # for production
spec:
  selector:
    app: project-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
