apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-server-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server-development
  template:
    metadata:
      labels:
        app: project-server-development
    spec:
      containers:
        - name: project-server-development
          image: learnforward2022/project-server-development:04ae58ff2808179ebb0e03bdcb0d79dff08fa703
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db_password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-host
                key: db_host
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: together-development-secrets
                key: GITHUB_CLIENT_ID
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: together-development-secrets
                key: GITHUB_CLIENT_SECRET
          - name: SECRET_JWT_KEY
            valueFrom:
              secretKeyRef:
                name: together-development-secrets
                key: SECRET_JWT_KEY
          ports:
            - containerPort: 8080
          command: ["sh", "-c"]
          args:
            - "yarn migration:development && yarn dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server
  template:
    metadata:
      labels:
        app: project-server
    spec:
      containers:
        - name: project-server
          image: learnforward2022/project-server:04ae58ff2808179ebb0e03bdcb0d79dff08fa703
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db_password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-host
                key: db_host
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: together-secrets
                key: GITHUB_CLIENT_ID
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: together-secrets
                key: GITHUB_CLIENT_SECRET
          - name: SECRET_JWT_KEY
            valueFrom:
              secretKeyRef:
                name: together-secrets
                key: SECRET_JWT_KEY
          ports:
            - containerPort: 8080
          command: ["sh", "-c"]
          args:
            - "yarn migration:production && yarn start"
