apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-server-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server-development
  template:
    metadata:
      labels:
        app: project-server-development
    spec:
      containers:
        - name: project-server-development
          image: learnforward2022/project-server-development:4ef34d01f69aed7644442e91f2f04bb0d8da0ebb
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db_password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-host
                key: db_host
          ports:
            - containerPort: 8080
          command: ["sh", "-c"]
          args:
            - "yarn migration:development && yarn dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server
  template:
    metadata:
      labels:
        app: project-server
    spec:
      containers:
        - name: project-server
          image: learnforward2022/project-server:a9a02b2ce84db7243065b2fd0ff91b7a34283911
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user
                key: db_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db_password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-host
                key: db_host
          ports:
            - containerPort: 8080
          command: ["sh", "-c"]
          args:
            - "yarn migration:production && yarn start"
