apiVersion: v1
kind: Service
metadata:
  name: project-server-loadbalancer # for production
spec:
  selector:
    app: project-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: project-server-development-loadbalancer # for development
spec:
  selector:
    app: project-server-development
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
